### ISSUE TITLE
User can unknowingly create/adjust a vault that quickly becomes liquidated

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#101]
## What is the Problem Being Solved?
UI work that compliments #6968 - see for more information that is adequately described there.

## Description of the Design

Vaults UI work for underlying contract work spec'd as https://github.com/Agoric/agoric-sdk/issues/6968 

(use lower price between current oracle price or next liquidation price when creating a vault or adjusting a vault (minting more IST) in lieu of MCR-LR calculation in avoid unwitting liquidation situations.

**Comment by otoole-brendan** [comment]
Another for the V+1 for now but add back in when 0 pile

**Comment by samsiegart** [comment]
Test comment

**Comment by otoole-brendan** [comment]
@samsiegart just confirming something I believe we already discussed - as it stands, this will be enforced on a contract-level so user will get offer error in wallet UI? (assuming they use endorsed UI - I understand there is a risk that they could a different UI which could circumvent this - but I'll admit I don't fully understand how)
