### ISSUE TITLE
ATOM logo not displayed correctly in Vaults UI

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#109]
## Describe the bug

Since ollinet redeploy on 2nd May, the ATOM logo is not appearing correctly in Vaults UI. See screenshots below (note, Devnet is not showing same issue).

![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/fd50c40a-a27f-409c-a9b9-81953347e437)

![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/02cbbb80-f8ae-4bed-b79a-3cdb40760807)
## To Reproduce

1. Launch ollinet vaults

## Expected behavior

ATOM logo should be displayed

## Screenshots

If applicable, add screenshots to help explain your problem, especially for UI interactions.

**Comment by samsiegart** [comment]
Confirmed fixed on the latest version https://bafybeiabllxyn5xkbuwecao4vztsixvrllttcnlprcy6mtvlsgqnapdw5i.ipfs.cf-ipfs.com/#/vaults
