### ISSUE TITLE
before "connect wallet", ATOM balance shows 0 when >0 is in my wallet

### ISSUE THREAD

**Issue by dckc** [Agoric/dapp-inter#119]
## To Reproduce

_what I did, anyway:_

1. used https://devnet.faucet.agoric.net/ to get some devnet BLD, ATOM
2. Use https://main.wallet-app.pages.dev/wallet/ to provisioned a smart wallet; saw 500 ATOM
3. went to https://app.inter.trade/?network=devnet
4. saw 0 ATOM Available

## Expected behavior

Show "??? ATOM Available" or omit that field or something.

## Platform Environment

- what OS are you using? what version of Node.js?
- what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

brave on linux. I don't think I'm using node nor the sdk

Inter protocol link includes `bafybeih3ieyxyphvnbwsk7ahmgk232z3tndfbuxth7y5273shhgz5juore`

instagoric shows
Chain: agoricdev-18
Revision Link: https://github.com/Agoric/agoric-sdk/tree/ea8c1c64911b4c58fb43635b25e17e3d50d0cf2a

## Screenshots

![image](https://github.com/Agoric/dapp-inter/assets/150986/8aad9cec-6ae7-4665-8e88-917691baf2c2)

**Comment by samsiegart** [comment]
I think the 0.00 balance is explainable enough with the big red "need to connect wallet" text that was cropped out:

<img width="277" alt="Screenshot 2023-05-20 at 12 16 10 PM" src="https://github.com/Agoric/dapp-inter/assets/8848650/429ae170-2a88-485e-89e2-87ed8b9f0fd1">

We could consider moving that text to replace where it shows 0.00 ATOM available though. I think "???" or "--" or something is too unsightly as a placeholder and doesn't make it clear it's referring to a balance.

**Comment by otoole-brendan** [comment]
I agree with @samsiegart here - we're training users to know this is where to check balance without having to glance at their wallet (once connected) and seeing a 0 balance alongside 'Need to connect wallet' red text is pretty intuitive imo.
Besides, showing 0 balance before wallet connection is a standard UX practice in DeFi from what I've researched (can point to many app chains in Cosmos that do so so there is clear precedent). 
My recommendation would be that we close this out as design is acceptable and clear as is.
