### ISSUE TITLE
Proposal: Change <title> from "Inter Protocol UI"

### ISSUE THREAD

**Issue by samsiegart** [Agoric/dapp-inter#120]
## Describe the bug

"Inter Protocol UI" is perhaps a bit too technical. A few options:
- Inter Protocol Interface
- Inter Protocol App
- App | Inter Protocol
- \<Keep it the same\>
- \<None of the above, comment below\>

**Comment by otoole-brendan** [comment]
Discussed with @samsiegart - our preference is to add some app specificity with 'Vaults | Inter Protocol'.
