### ISSUE TITLE
Replace 'endorsed' with 'referenced' on Vaults jumper page

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#125]
## What is the Problem Being Solved?
Avoid the use of 'endorse(d)' in favor of 'reference(d)'.

Note there will be an accompanying ticket to change same in Econ Gov UI.

## Description of the Design
Change 'Looking up latest endorsed UI' to 'Looking up latest referenced UI' on for Vaults jumper page.

## Security Considerations
N/A

**Comment by samsiegart** [comment]
We want to show "Looking up latest version of dapp..." instead now
