### ISSUE TITLE
Wallet Connect hangs for pre-Vaults chain upgrade created wallets that didn't make a transaction

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#151]
## Describe the bug

Wallet Connect hangs for wallets that were created before mainnet 1b/vaults chain upgrade that had not yet completed a PSM transaction.

From initial investigation into some offending wallets - it appeared that path exists to vstorage but the data is empty

This is likely affecting a number of wallets - we need to determine what the cause is, how to rectify and impact (# of wallets it affects by querying # of wallets in this state).

Further async commentary on issue https://agoricopco.slack.com/archives/C03FUCJV2J2/p1687874738588889 and https://agoricopco.slack.com/archives/C04JJ58RUPM/p1687811340695409 

## To Reproduce

1. Have created a wallet before mainnet 1b/vaults upgrade
2. Have not completed PSM transaction
3. Attempt to connect to Vaults UI with same wallet
4. Wallet Connect hangs

## Expected behavior

Wallet should connect without issue

## Platform Environment

- what OS are you using? what version of Node.js?
- is there anything special/unusual about your platform?
- what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots

If applicable, add screenshots to help explain your problem, especially for UI interactions.

**Comment by dtribble** [comment]
The user was able to connect the wallet to the PSM app, do a PSM txn, and then proceed to connect to the Vaults ui.

**Comment by samsiegart** [comment]
This was fixed
