### ISSUE TITLE
Remove notification banner from dapp-inter (no longer required as no longer relevant)

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#203]
## What is the Problem Being Solved?
There is a currently a banner appearing on dapp-inter-jumper notifying users of an issue that was resolved as of last night and therefore it is no longer required.

The jumper banner needs to be disabled/removed.

## Description of the Design
Remove/disable jumper banner.

**Comment by samsiegart** [comment]
Done
