### ISSUE TITLE
Add outage/notice banner for walletFactory upgrade (to dapp-inter-jumper)

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#204]
## What is the Problem Being Solved?
We need to add a banner to dapp-inter jumper to notify users of a imminent possible outage with walletFactory core eval deployment

## Description of the Design

Notice: Wallet functionality will shortly be upgraded as per Proposal 49 (Upgrade Smart Wallet to support NFTs) - due to execute at ~ 12:37 PDT. While we do not anticipate an outage we do expect a slow-down for several minutes.

**Comment by samsiegart** [comment]
Done
