### ISSUE TITLE
Enable service disruption banner on dapp-inter-jumper for Kryha Mainnet deployment

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#205]
## What is the Problem Being Solved?
Use [our new network-config](https://main.agoric.net/network-config)  to enable and display a service disruption message to dapp-inter users on the dapp-inter-jumper page so they are aware of impact durin Kryha mainnet deployment

## Description of the Design

Notice: New contract functionality will soon be upgraded as per Proposal 53 (KREAd-rc1 to Mainnet). We do not anticipate an interruption of service but transactions may be delayed around the upgrade time on Oct 01, 2023 1:18:31 PM PDT

**Comment by ivanlei** [comment]
Done

<img width="1070" alt="Screenshot 2023-10-01 at 1 44 34 PM" src="https://github.com/Agoric/dapp-inter/assets/1002798/d7bbf393-d3e4-4717-8129-82a2158f60ab">
