### ISSUE TITLE
dapp-inter -Message banners on inter.trade to sets the expectation for an impending mainnet upgrade

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/dapp-inter#212]
For Upgrade12 Add a message banner on inter.trade that sets the expectation for an impending mainnet upgrade/temporary disruption of services

**Comment by samsiegart** [comment]
There's no banner on the actual vaults dapp, just in the jumper page before being sent to the vaults dapp. Assuming this is sufficient and we don't need to build a new feature to show a banner inside vaults, can we close this?

**Comment by aj-agoric** [comment]
I agree here, so long as the message is relayed. We can close yes.

**Comment by aj-agoric** [comment]
Marking as done per Sam's comment above
