### ISSUE TITLE
"Cosmos Swap" in Leap Elements modal hangs without recognizing transaction has completed

### ISSUE THREAD

**Issue by rowgraus** [Agoric/dapp-inter#221]
## Describe the bug
When conducting a "Cosmos Swap" using Leap Elements, the modal hung apparently without receiving notification that transactions have completed.  

On beginning the swap, Keplr pops up to sign, and the first set of transactions show a timer as though they are waiting to complete.  The modal spins indefinitely (waited >10 minutes at one point), but inspection of assets in my wallet showed that the full set of transactions (multiple IBC transfers with Osmosis swap in between) completed.  None of those intermediate steps showed completion either

Same experience on multiple attempts.

## To Reproduce
Navigate to https://bafybeifijh5wewd3da3tal3ybmlzojkn5texjyr5t5hrqtxkd52lspm7ty.ipfs.cf-ipfs.com/
Click Deposit Funds
Select Cosmos Swap
Attempt to perform a swap ending with assets on the Agoric chain
Observe modal behavior.

## Expected behavior

All intermediate steps should show completion within seconds of them completing

## Platform Environment

- what OS are you using? what version of Node.js?
MacOS, Chrome, Keplr
- is there anything special/unusual about your platform?
No

## Screenshots

If applicable, add screenshots to help explain your problem, especially for UI interactions.

**Comment by rowgraus** [comment]
Adding detail:
Attempted swaps were
ATOM on Cosmos Hub -> BLD on Agoric
ATOM on Cosmos Hub -> IST on Agoric

Note that all swaps actually completed on first try, but the modal didn't seem to receive any updates

**Comment by aj-agoric** [comment]
closing as can not reproduce
