### ISSUE TITLE
Enable service disruption banner on dapp-inter-jumper for stOSMO mainnet deployment

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#232]
## What is the Problem Being Solved?
Use [our new network-config](https://main.agoric.net/network-config) to enable and display a service disruption message to dapp-inter users on the dapp-inter-jumper page so they are aware of potential impact of stOSMO deployment.

## Description of the Design

'Notice: Wallet functionality will shortly be upgraded as per Proposal 68 (Enable stOSMO Vault) - from 2024-02-12 | 10:20AM -10:30AM Pacific. While we do not anticipate an outage we do expect a slow-down for several minutes.'

**Comment by samsiegart** [comment]
Done
