### ISSUE TITLE
Add service outage banner for stTIA core eval deployment

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#234]
What is the Problem Being Solved?

Use [our new network-config](https://main.agoric.net/network-config) to enable and display a service disruption message to dapp-inter users on the dapp-inter-jumper page so they are aware of potential impact of stTIA deployment.

Description of the Design

'Notice: Wallet functionality will shortly be upgraded as per Proposal 69 (Enable stTIA Vault) - from 2024-02-14 | 09:26AM -10:36AM Pacific. While we do not anticipate an outage we do expect a slow-down for several minutes.'

**Comment by samsiegart** [comment]
Banners are up now in app.inter.trade and psm.inter.trade
