### ISSUE TITLE
Minting Fee does not shown/applied in Vault Summary

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#248]
## What is the Problem Being Solved?

When a user creates a vault or adjusts a vault - a minting fee applies to the minted IST amount - which is added to the user's IST overall debt amount. This actual amount is not reflected in the 'Vault Summary' preview and so it's not clear to the user what amount that is. 

The dollar amount should be included as a line item so users' can clearly see the minting fee that is being incurred and added to their overall IST debt with the mint action they are taking

## Description of the Design

- [ ] For new vault creation -> Show calculated minting fee based on user-specific IST mint amount in the vault summary tile e.g. if minting fee 0.05% user opening 1000IST vault incurs 50IST charge which should be shown as ->  Minting Fee......0.5% (50 IST)
- [ ] For vault adjustment (+minting more IST action) -> add 'Minting Fee' and show adjustment as a line item between 'Debt' and 'Collateralization Ratio' e.g. if user is minting an additional 1000IST at 0.5% then show as  'Minting Fee (0.05%)................50IST (added to debt)' (@samsiegart this might be a bit clunky so let's discuss if there's a better way to illustrate this line item)

**Comment by samsiegart** [comment]
In "Adjust Vault", the new debt total already includes the minting fee (see below, minting 100 IST):

<img width="444" alt="Screenshot 2024-03-07 at 2 15 15 PM" src="https://github.com/Agoric/dapp-inter/assets/8848650/6a9d258b-d9c5-4e6e-9540-81ad4f874533">

Maybe it's best to have an `(i)` tooltip explaining it's the total of `existing debt + newly minted + minting fee`. 

In "Create Vault", maybe we could show a line below minting fee, like "Debt After Minting Fee" or something:

<img width="438" alt="Screenshot 2024-03-07 at 2 18 58 PM" src="https://github.com/Agoric/dapp-inter/assets/8848650/35828d39-e75c-42ab-8598-23aee3ecb43e">

That would make it clearer that it's not charging you IST on the transaction, but rather it's being added to the debt.

**Comment by otoole-brendan** [comment]
I knew the minting fee was being reflected to the new debt amount - it's more about better communicating to users a) that is the case but more importantly b) what that amount is. 

For create vault - yep I think I largely agree but call it 'Debt' or 'Your Debt Balance' and include tool tip explainer:

Depositing........................X stTIA
Minting.............................1000IST
Your Debt Balance............1100IST (with a tooltip that explains this is sum of minted IST + minting fee)

For Adjust vault where minting more - follow similar so 'Your Debt Balance' line item with tool tip explainer of components then also adding the Minting Fee parameter like you suggest.

Depositing.......................X stTIA
Minting.............................500IST
Your Debt Balance............1150 (Existing debt (1100) + minting fee (50) + accrued stability fee (X)
------------------
Min Collateralization Ratio.......X %
Liquidation Ratio......................X %
Stability Fee.............................X %
Minting Fee..............................X %
