### ISSUE TITLE
EC needs to be able to add and remove node operators from oracle network

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#25]
## What is the Problem Being Solved?

The EC needs to be able to add and remove oracle node operators by proposing and voting on said action for vaults release as a short-medium term measure until we pivot to self-governing oracle network. 

The EC should be able to make changes to oracle node network setup by removing any node operator (for whatever reason, but typically this is for risk purposes and to take emergency action to preserve price integrity. Similarly, the EC may choose to replace this bad actor or increase the number of node operators (greater than starting 5) to hedge against fewer points of failure.

The EC should be able to select any node operator (possible from a drop-down) and then propose to remove. Similarly, the EC needs to be able to add a new operator (not sure how best to visualize this in UI as it requires input of a node operator with related underlying information which would not be known until future date - open to suggestions)

## Description of the Design

```[tasklist]
### Contract changes
- [ ] https://github.com/Agoric/agoric-sdk/issues/6701
```

## Security Considerations
Unknown

**Comment by otoole-brendan** [comment]
@turadg should this be in econ-gov-ui repo vs dapp-inter? Would you also be able to please estimate this?

**Comment by turadg** [comment]
Issue moved to [Agoric/dapp-econ-gov #35](https://github.com/Agoric/dapp-econ-gov/issues/35) via [**Zenhub**](https://www.zenhub.com/)
