### ISSUE TITLE
Unable to submit transaction due to fee payer address error

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#252]
## Describe the bug

Any attempt to submit a transaction on latest version of `'main'` dapp-inter UI results in below error message:

'Offer failed: Error: Broadcasting transaction failed with code 9 (codespace: sdk). Log: fee payer address: agoric1qqqqqpcqqqqqqqqqqvqqqqqpqqpsqqqzqqqqqqgyqqqqq3mdlac does not exist: unknown address'.

Dapp-psm transactions are not affected.

## To Reproduce

1. Go to https://bafybeicj2owk2ae6qhwnicclk7jjcbwianrf6m32h6tolkmnv7jqh3zcle.ipfs.cf-ipfs.com/ 
2. Select 'Emerynet'
3. Connect Wallet
4. Attempt to Create/Adjust/Close vault
5. See error

## Platform Environment

- what OS are you using? what version of Node.js?
- is there anything special/unusual about your platform?
- what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Additional context

Upgrade 14 RC0 testing against http://bafybeiaacac4p2xuuljvwdgzr4dgh3zgjw6w2lm4h4ut3qbf4b5nyoximy.ipfs.cf-ipfs.com/?#/vaults ~2 weeks ago was successful - did not run into this same issue

## Screenshots

<img width="626" alt="image" src="https://github.com/Agoric/dapp-inter/assets/93355546/b587489f-5416-4698-a913-89cf8063fcb7">

**Comment by otoole-brendan** [comment]
From @samsiegart:  It seems when we [updated @agoric/cosmic-proto](https://github.com/Agoric/dapp-inter/blob/b2f624b90e342199c5ccd1bafc82f66cd7d600af/package.json#L18) in dapp-inter we were seeing issues broadcasting transactions. It might be because of the message types that we import [here](https://github.com/Agoric/ui-kit/blob/8fc28e8bfefd55f0503e54abd78ff8fdb789dc86/packages/web-components/src/wallet-connection/signerOptions.js#L6) not matching what the upgrade-14 chain expects (would they be different)?

**Comment by samsiegart** [comment]
Closing this because this because the broken version was never an endorsed UI in mainnet, emerynet, or elsewhere. It was just the latest `main` that was broken at one point and is now fixed as of https://github.com/Agoric/dapp-inter/pull/253.
