### ISSUE TITLE
New stATOM vault not appearing in dapp-inter FE after what looks like successful vault creation txn

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#263]
## Describe the bug

Created stATOM vault - thought successfully in UI (got pop-up) but not shown in my vaults view. Suspect something UI/client side as:

- stATOM balance was deducted (10 stATOM)
-wallet and Keplr show deducted 
-can see wallet spend action on block explorer https://agoric.explorers.guru/transaction/346192D7890D42D3DCD654CCF7C9CD6A4244E9FFE0A0838E8D1535BCB2425B5A 

## To Reproduce

1. Got app.inter.trade
2. Create a stATOM vault (or maybe another vault not sure)
3. stATOM vault does not appear despite txn looking like it succeeds
4. Refreshing does nothing

## Expected behavior

stATOM vault should appear

## Additional context

Tried changing between KJnodes and Polkachu for RPC endpoint. KJ nodes won't load my wallet at all but Polkachu gives CORS policy error (amongst other errors) 

## Screenshots

<img width="631" alt="image" src="https://github.com/Agoric/dapp-inter/assets/93355546/9e5c6a99-ef34-4bcb-906d-dd07b6a997a2">

<img width="631" alt="image" src="https://github.com/Agoric/dapp-inter/assets/93355546/8be3885d-ace7-4a81-9bbc-a6a51a004ff1">

**Comment by turadg** [comment]
RPC server failure, not a code problem. 
```sh
AGORIC_NET=main  agoric wallet show --from=agoric10td8wuyznhe0eq8spm3pzt65nejf6phn8vrjgh
```
times out with error:
```
agoric: (Error#1)
Error#1: RPC failure (https://agoric.rpc.kjnodes.com:443,https://agoric-agor-rpc.polkachu.com:443): cannot read data of published.agoricNames.brand: invalid json response body at https://agoric.rpc.kjnodes.com/abci_query?path=%22/custom/vstorage/data/published.agoricNames.brand%22&height=0 reason: Unexpected token '<', "<html><bod"... is not valid JSON
```
because that abci_query times out. 

I'll leave this open in case PM wants the solution to include better user feedback in this event.

**Comment by erights** [comment]
Note that the underlying cause is fixed at https://github.com/pinojs/pino/pull/1939 . Would adopting that difference as a (simple!) patch work in the meantime, until we can upgrade to depend on a pino with that fixed?

Attn @samsiegart @kriskowal

**Comment by turadg** [comment]
@erights I think you're speaking to some of the errors in the console, but this is about the UX. 

We still do need to solve the console output, which is in progress: https://github.com/Agoric/dapp-inter/pull/264/

**Comment by erights** [comment]
Aha https://github.com/Agoric/dapp-inter/pull/264 !

Thanks @0xpatrickdev !

**Comment by otoole-brendan** [comment]
For when you're back @samsiegart - I'm keen to understand in this scenario why we didn't show the user the connection issue dialog (like we do when an RPC connection breaks/is flaky) - which directs them to change RPC/API endpoint via the connection settings?
(we should be able to know and alert users appropriately if it's connection/rpc related in the UI and not rely on them figuring it out via console logging)

**Comment by otoole-brendan** [comment]
> The CORS error is not coming from the Agoric RPC, the logs show it's coming from coingecko API. which is probably being fetched from the leap elements IST onboarding modal. Are you still able to reproduce this @otoole-brendan? I think we had RPC issues last week? It could just be that the RPC was not giving the latest data, or taking a really long time to update. As you said we do have retry logic that will show the error dialog after a few unsuccessful attempts, and nothing from the logs indicates we got an error response from the RPC, so I'm not inclined to think that's the part that's broken.

No it was resolved and I cannot reproduce anymore. So sounds like we can chalk it up to those RPC issues and close?

**Comment by samsiegart** [comment]
> No it was resolved and I cannot reproduce anymore. So sounds like we can chalk it up to those RPC issues and close?

Yea, can't say 100% for sure without reproing but I'll close and we can reopen if it pops up again
