### ISSUE TITLE
Dapp-Inter E2E Testing Completed

### ISSUE THREAD

**Issue by toliaqat** [Agoric/dapp-inter#265]
## What is the Problem Being Solved?
All required E2E tests are added for dapp-inter and running in our CI.
CI will be running for each PR to test if the PR breaks anything in our code against the latest agoric-sdk (local chain).
A periodic CI will also be running against emerynet to test if the master still works with emerynet.

**Comment by rabi-siddique** [comment]
@otoole-brendan 

I reviewed the tests for dapp-inter and needed to clarify a few points. Specifically, regarding the test `Withdraw collateral from closed vault` it seems to be designed for use with Mainnet. I couldn't find an option to select a local chain or a testnet chain via the dropdown menu, as seen in the leap elements. Can you confirm if it functions the same?

**Comment by rabi-siddique** [comment]
I need clarification regarding the test for Testing Leap Elements when adding a new collateral type. Do we just need to verify that Leap Elements are working properly? Could you explain the workflow for this test? So far, I've only interacted with Leap Elements through the Deposit Atom button or the Withdraw Atom button as shown in the screenshots. Am I overlooking something?

![image (2)](https://github.com/Agoric/dapp-inter/assets/60459172/bfe85242-fd3d-41e3-995b-bf9c83419433)
![image (3)](https://github.com/Agoric/dapp-inter/assets/60459172/f1fb004a-fbf6-45fb-a3d4-85dbbf7d3d9e)

**Comment by rabi-siddique** [comment]
One last thing about `Testnet UI URL accessible through the relevant Instagoric 'jumper' URL`? Fraz is currently transitioning dapp-inter test cases to emerynet. Is this the correct instagoric jumper URL for emerynet: `https://emerynet.agoric.net/`?

**Comment by otoole-brendan** [comment]
> [@otoole-brendan](https://github.com/otoole-brendan)
> 
> I reviewed the tests for dapp-inter and needed to clarify a few points. Specifically, regarding the test `Withdraw collateral from closed vault` it seems to be designed for use with Mainnet. I couldn't find an option to select a local chain or a testnet chain via the dropdown menu, as seen in the leap elements. Can you confirm if it functions the same?

@rabi-siddique That test case is satisfied by closing a vault and ensuring that the user receives their collateral that was locked in the vault. It can be tested on Mainnet and Emerynet.

The other use case is claiming collateral on a vault that has been liquidated but has had some collateral returned to it (i.e. via happy path liquidation) where user clicks on liquidated vault to withdraw returned collateral and close the vault

**Comment by rabi-siddique** [comment]
> > [@otoole-brendan](https://github.com/otoole-brendan)
> > I reviewed the tests for dapp-inter and needed to clarify a few points. Specifically, regarding the test `Withdraw collateral from closed vault` it seems to be designed for use with Mainnet. I couldn't find an option to select a local chain or a testnet chain via the dropdown menu, as seen in the leap elements. Can you confirm if it functions the same?
> 
> @rabi-siddique That test case is satisfied by closing a vault and ensuring that the user receives their collateral that was locked in the vault. It can be tested on Mainnet and Emerynet.
> 
> The other use case is claiming collateral on a vault that has been liquidated but has had some collateral returned to it (i.e. via happy path liquidation) where user clicks on liquidated vault to withdraw returned collateral and close the vault

@otoole-brendan  We've completed the section on `closing a vault and ensuring that the user receives their collateral.`

Regarding the aspect of `claiming collateral` I suggest incorporating it into the Liquidation Test Cases?

**Comment by rabi-siddique** [comment]
> Yeah that sounds fine - it's confusing because it's a test of the dapp-inter UI but it's specifically testing a liquidation test case

Based on that, do you think we cover the test cases we've defined [here](https://docs.google.com/spreadsheets/d/141xYfXMeul1_1IeaTiyHvjoVA2KttvhNyu2aYw5cglY/edit#gid=928950436) for dapp-inter?

Here is the CI run of these test cases, let me know if you think something is missing or if we can improve or add:

https://github.com/Agoric/dapp-inter/assets/60459172/6a5e4c94-cbe8-42d6-b7fa-99305ab6b75e
