### ISSUE TITLE
Change referenced block explorer from Big Dipper to Nodes Guru (In Leap Elements dialog for txns from Agoric)

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#267]
## What is the Problem Being Solved?

Big Dipper block explorer is no longer operational. Leap Elements directs users to open txn on Bid Dipper when sending from Agoric chain which results in a 404 error. This needs to be pointed at NodesGuru (https://agoric.explorers.guru/)

## Description of the Design

This hyperlinked text currently points to Big Dipper but needs to point to a working block explorer like Nodes Guru (https://agoric.explorers.guru/) :

<img width="931" alt="image" src="https://github.com/Agoric/dapp-inter/assets/93355546/66a647d4-9f7d-4c45-a8d5-6d715fceabe8">

**Comment by samsiegart** [comment]
This might be tricky because we'll have to get the leap team to update it, and there's a rendering bug in newer versions of leap elements. I previously brought it up to them in telegram (the leap elements repo isn't public) and just followed up about it. Maybe I can use https://www.npmjs.com/package/patch-package to tweak the explorer url in the meantime

**Comment by samsiegart** [comment]
It appears that the block explorer might be coming from leap's API, rather than coded into the component itself. I've messaged the leap team to verify and potentially update it on their backend.

**Comment by samsiegart** [comment]
Leap team confirmed that this is an API change on their part and they'll be updating it, will report back when the change goes through and I can test it

**Comment by samsiegart** [comment]
@otoole-brendan The leap team informed me that they've made this change now, so we should see the nodes guru explorer in leap elements. Can you confirm that this is fixed? Reassigning to you.

**Comment by otoole-brendan** [comment]
@samsiegart confirm this is fixed
