### ISSUE TITLE
Total # of active vaults not including vaults with zero IST debt

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#311]
## Describe the bug

App.inter.trade shows `Total # of active vaults `which uses sum of `numActiveVaults`. However it does not include vaults with zero IST debt and therefore is technically incorrect and underreporting the number of active vaults.

Info.inter.trade accounts for these vaults and includes them in the count. 

Update dapp-inter to use this query to return the correct value ([Slack reference](https://agoricopco.slack.com/archives/C038TM0EUKG/p1718062228425269?thread_ts=1718057067.747099&cid=C038TM0EUKG))

curl -s 'https://api.subquery.network/sq/agoric-labs/agoric-mainnet-v2' -H 'Content-Type: application/json' --data-binary '{
  "query": "query {\tvaults(filter: {state: {equalTo: \"active\"}}) {totalCount}}"
}' | jq .

## To Reproduce

1. Compare $ of active vaults visible on app.inter.trade with that of info.inter.trade

## Expected behavior

Should in include vaults that have zero IST debt

**Comment by samsiegart** [comment]
@otoole-brendan Do we have subquery indexers for testnets as well? At the very least, we won't have it for local networks. I can make the dapp use this subquery data for mainnet, and all other networks it would still use the same old data if that works.

**Comment by otoole-brendan** [comment]
> [@otoole-brendan](https://github.com/otoole-brendan) Do we have subquery indexers for testnets as well? At the very least, we won't have it for local networks. I can make the dapp use this subquery data for mainnet, and all other networks it would still use the same old data if that works.

that's fine @samsiegart ! @toliaqat can answer about indexers for testnets - I'm not sure
