### ISSUE TITLE
Add banner to dapp-inter

### ISSUE THREAD

**Issue by samsiegart** [Agoric/dapp-inter#334]
The dapp-inter-jumper is no longer used, as app.inter.trade serves the dapp directly. We should add a way to show "dappInterJumperBanner" from the network-config natively inside the dapp now.

**Comment by otoole-brendan** [comment]
@samsiegart I think this can be closed now because 335 is merged and deployed right?

**Comment by samsiegart** [comment]
> @samsiegart I think this can be closed now because 335 is merged and deployed right?

Yea will close
