### ISSUE TITLE
FE for IBC asset transfer

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#34]
## What is the Problem Being Solved?

Current Vaults design requires users to have their collateral asset on the Agoric Chain to be able to create a vault (or add more collateral to a vault).

Users need to be able to transfer their ATOM for example from it's source chain (Cosmos Hub) to Agoric Chain either before or during vault creation in order to be able to lock up that collateral and create a vault/mint IST.

Absence of a suitable FE for this forces users to user Keplr's manual IBC transfer method which is at best a clunky, error-prone awful experience and at worst a reputation-damaging, user-repellant that will all but guarantee low uptake/use.

## Description of the Design

There are two ways to approach this thatI know of
1) add deposit/withdraw feature to Agoric Smart Wallet where user will need to initiate and complete asset transfer (a al Osmosis)
or
2) add an asset transfer model/FE to the Vaults UI that guides users through each step, initiates the transactions, notifies user to approve in wallet etc, completes transfer, then shows the users updated asset balance on Agoric chain that they is now available to lock up as collateral

The first option would mean the user having to spend more time in their smart wallet, something Product agrees we want to avoid (fragmented experience amongst others). The second option is better UX overall, more seamless and certain to delight users (although it's likely expected by users in which case they will appreciate us keeping in line with others).

(This [design mock-up by Ekko](https://www.figma.com/file/r0WcCjyS0LAOalFGV4DSuk/agoric-v1?node-id=1952%3A8449&t=zahG8gb4SvXOLYiR-0) is in progress.)

Storytime:

- Peter wants to use Inter Protocol's exciting new vaults dapp to lock up his 100ATOM and mint a respective amount of IST.
-He hits the Vaults UI, specifies the vault type he'd like to open and then is guided to a step that prompts him to connect his wallet. Once he connects his wallet, he realizes he has no ATOM on the Agoric chain and so he can't create a vault. 
-He is prompted to start an asset transfer which is a neat modal that pops up and guides him through the process:
1) Enter amount you wish to transfer (to Agoric Chain)
2) Approve Transfer in Wallet 
3) Transfer ATOM to Agoric 
4) Success (You’ve successfully transferred X ATOM to Agoric. You can now use this as collateral to open/adjust your vault) or
Error Message (Transaction Failed Your transaction failed. Cancel or Try Again...or something similar)

-Peter has completed transferring the assets he wishes to use as collateral to the Agoric chain and is ready to configure vault/lock-up collateral.
-Peter can now see he has 100ATOM available on the Agoric chain that he can lock up as collateral.
-Peter completes configuration of his vault, submits the offer to his Smart Wallet, approves in his smart wallet and now has a vault and minted IST.

## Security Considerations
TBD

## Test Plan
TBD

**Comment by dckc** [comment]
for reference:

 - [SigningStargateClient.sendIbcTokens](https://cosmos.github.io/cosmjs/latest/stargate/classes/SigningStargateClient.html#sendIbcTokens)

**Comment by dckc** [comment]
### Broadcasting on non-Agoric chains

A complication is that the transaction is broadcast on the sending chain; in the example case, the Cosmos hub. Odds are this is a well-trodden path for the user's Keplr wallet, but still... all our connection setup logic to date assumes we're broadcasting to an Agoric chain. (Fortunately, it's straightforward to convert an `agoric1...` address into a `cosmos...` address with the same public/private key using [fromBech32](https://cosmos.github.io/cosmjs/latest/encoding/modules.html#fromBech32) and [toBech32](https://cosmos.github.io/cosmjs/latest/encoding/modules.html#toBech32).)

The connection details are supposed to be available in [the chain registry](https://github.com/cosmos/chain-registry). It might be possible to have this dapp handle new source chains dynamically, but given that adding a new asset is a whole-chain-governance action, it seems more likely that we'll release an update for each new source chain.

**Comment by dckc** [comment]
### Osmosis doesn't use `sendIbcTokens`

 
Interesting... searching [osmosis-frontend](https://github.com/osmosis-labs/osmosis-frontend)  `sendIbcTokens` turns up **nothing**.

https://github.com/osmosis-labs/osmosis-frontend/blob/master/packages/stores/src/tx/ibc/ibc-transfer.ts seems to be the central part of their implementation

https://github.com/osmosis-labs/osmosis-frontend/tree/master/packages/stores/src/ibc-history
main file (index.ts) is 570 LOC

**Comment by otoole-brendan** [comment]
adding [Stride](https://app.stride.zone/) screenshot to help visualize option 2 as this is desired behavior: 
![image](https://user-images.githubusercontent.com/93355546/213558865-e5dacedb-7e47-4b0a-8529-74f5dda30c0c.png)

**Comment by otoole-brendan** [comment]
Following discussion, the design for this has changed. The asset transfer functionality will be added to smart wallet UI, not vaults UI for several reasons including being able to use for other dapps in future.

**Comment by otoole-brendan** [comment]
Issue moved to [Agoric/wallet-app #50](https://github.com/Agoric/wallet-app/issues/50) via [**Zenhub**](https://www.zenhub.com/)
