### ISSUE TITLE
remove mainnet from the repo

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/dapp-inter#36]
Refs: https://github.com/Agoric/agoric-sdk/issues/4350

## What is the Problem Being Solved?

The builds point to mainnet but we can't host, or deploy anything in CI, which points to mainnet (agoric-3).

## Description of the Design

One option is to introduce an environment variable, or alternate build flag to enable a "production" mode, which includes only the production config, so that default building of the project will only have testnet configurations

Another is to make this repo completely unaware of production uses. Make the endpoint selection be defined by a config file and when this code is purposed for a new network, anyone can modify the config file and build. One kink is that the config file is in the repo so they might trip up and commit their changes. To prevent that we could have config.ts read an optional JSON file for overrides. The override file would be listed in .gitignore so it doesn't ever get into the repo.

## Test Plan

No references to mainnet in the repo.

**Comment by samsiegart** [comment]
I think something like this should work (reference https://vitejs.dev/guide/env-and-mode.html#env-files):

Somewhere in `package.json`
```
// To build for production
VITE_SHOW_NETWORK_DROPDOWN=true yarn build
```

Somewhere in source code
```
if (import.meta.env.VITE_SHOW_NETWORK_DROPDOWN) {
  // Show network dropdown
} else {
  // Default to prod network
}
```

**Comment by turadg** [comment]
This is a change in spec so it's a Work Item, not a Bug.

The problem to be solved is… the build always has production endpoints. Why is that a problem? Is it that the default build endorses a particular network with real assets? Why is that not a problem for a non-default build?

The proposed design is that by default the network dropdown doesn't include production endpoints. That means the Mainnet entry?

The code example conditions the presence of the dropdown entirely. I don't think that would solve the problem.  To come up with an appropriate design I think we need the problem fully specified.

**Comment by samsiegart** [comment]
And by "production builds" I mean maybe have a build rule that can spit out a build with the appropriate env variables for someone else to use

**Comment by turadg** [comment]
> The problem to solve is--we can't host, or deploy anything in CI, which points to mainnet (agoric-3).

Ok. So the expectation is that some other entity that wants to point this code to mainnet can run some script to produce a build that points to it.

In that case, I don't think we should complicate any of the code with this concern. The app has a menu for selecting between networks. The set of networks is in a configuration file, `config.ts`. If someone wants their build to have a different set of networks, they modify the config.

One kink is that the config file is in the repo so they might trip up and commit their changes. To prevent that we could have `config.ts` read an optional JSON file for overrides. The override file would be listed in `.gitignore` so it doesn't ever get into the repo.

**Comment by samsiegart** [comment]
Sounds plausible to me. I'm happy to just take mainnet out of the config for now and let the rest be an exercise for the reader. I figured we also might want to remove the dropdown just for aesthetic/ux reasons in production.
