### ISSUE TITLE
Add Legal Disclaimer to Vaults UI

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#54]
## What is the Problem Being Solved?
Similar to PSM and Wallet UI, we need to serve users with a legal disclaimer upon accessing the UI for the first time. User must accept to be able to continue
## Description of the Design

Same design as PSM: https://github.com/Agoric/agoric-sdk/issues/6491 . Copy TBD once Legal confirms.

## Security Considerations
N/A
## Test Plan
To be tested during smoke testing

**Comment by samsiegart** [comment]
@otoole-brendan I'm not sure if we wanted the exact wording as PSM or we're waiting for new wording. Assigned to you to please either confirm we want the same or update the issue with new wording, then you could assign it back to me.

**Comment by otoole-brendan** [comment]
@samsiegart you're right - this wording is currently being reviewed by Legal and Dean to determine if it is sufficient to apply to Vaults or needs tweaking. Will reassign when that is known.

**Comment by otoole-brendan** [comment]
Update: Aligned requirements with Legal - awaiting for updated copy from them.

**Comment by otoole-brendan** [comment]
@samsiegart Finalized legal copy for disclaimer:

This website may provide access and use of certain applications and services (“Applications”). You will only use the Applications as directed and reasonably intended by this website. Certain Applications are provided as free, public, or open-source software, and those Applications are governed by separate terms. As between you and the website providers, the website providers retain all right, title, and interest in and to the Applications except as set forth in this Disclaimer. You are responsible for any fees, including blockchain transaction fees, related to your use of the Applications.


Your use of the Applications involves various risks, including, but not limited to, losses while digital assets are being supplied to or used with the Applications. Additionally, access to Applications through other web or mobile interfaces is at your own risk. You are responsible for conducting your own diligence on those interfaces to understand the fees and risks they present. You acknowledge and agree that you assume full responsibility for your use of the Applications. You acknowledge and agree that any information you send or receive during your use of the Applications may not be secure and may be intercepted or later acquired by unauthorized parties. 


THE APPLICATIONS ARE PROVIDED “AS IS”, AT YOUR OWN RISK, AND WITHOUT WARRANTIES OF ANY KIND. THE APPLICATIONS ARE PROVIDED WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES OR REPRESENTATIONS REGARDING THE QUALITY OF THE SERVICES AND ASSOCIATED SOFTWARE (ON-CHAIN AND OFF-CHAIN) WHETHER IN TERMS OF FUNCTIONALITY, RELIABILITY, USABILITY, EFFICIENCY, MAINTAINABILITY, HARDWARE COMPATIBILITY, CONTINUOUS OR ERROR-FREE OPERATION, OR COMPLIANCE WITH YOUR REQUIREMENTS OR SPECIFIC BUSINESS GOALS. The Providers hereby expressly disclaim, waive, release and renounce all warranties, express or implied, including, without limitation, any warranty of merchantability, fitness for a particular purpose, title, or non-infringement.


To the maximum extent permitted by law, no individual or entity, or such party’s affiliates, or any of their respective licensors, service providers, employees, agents, providers, developers, validators, voting members or community members, involved in creating, operating, providing, or maintaining the Applications or this website, including BLD stakers and members of the Economic Committee, (collectively referred to as “Providers”) will be liable for any claims or damages whatsoever associated with your use, inability to use, or your interaction with other users of the Applications, including but not limited to any direct, indirect, incidental, special, exemplary, punitive or consequential damages, or loss of profits, cryptocurrencies, tokens, or anything else of value, and in no event will Providers be liable for any claims or damages whatsoever associated with decisions made in connection with the Applications or this website. 


Solely to the extent the previous section is not permitted by applicable law, THE MAXIMUM LIABILITY OF THE PROVIDERS TO YOU IN CONNECTION WITH THE APPLICATIONS OR THIS WEBSITE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES WHICH YOU MAY INCUR, HOWSOEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, AND ALL CLAIMS ARISING OUT OF OR RELATING TO YOUR ACCESS TO OR USE OF (OR YOUR INABILITY TO ACCESS OR USE) ANY PORTION OF THE APPLICATIONS, INCLUDING, WITHOUT LIMITATION, ANY LOSS OF PROFITS (WHETHER INCURRED DIRECTLY OR INDIRECTLY), LOSS OF GOODWILL OR BUSINESS REPUTATION, LOSS OF DATA, COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, OR ANY OTHER INTANGIBLE LOSS, EVEN IF THE POSSIBILITY OF SUCH DAMAGES IS FORESEEABLE OR HAS BEEN ADVISED, IS LIMITED TO THE GREATER OF (I) THE TOTAL OF ALL AMOUNTS ACTUALLY PAID BY YOU TO A PROVIDER IN CONNECTION WITH THE APPLICATIONS IN THE 3 MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE LIABILITY OR (II) USD$100.


You acknowledge and agree that the Providers have made the Applications available to you in reliance upon the warranty disclaimers and limitations of liability set forth herein, which reflect a reasonable and fair allocation of risk between you and the Providers and form an essential basis of the bargain. The Providers would not be able to provide the Applications to you without these limitations.


In no circumstance shall any BLD staker or member of the Economic Committee (each a “Member”) be deemed to be personally liable for any damages which may stem from their involvement in or activities related to exercising their rights or obligations as a Member. No Member will be obligated personally for any debt, obligation, or liability of BLD stakers as an aggregate (whether entered into collectively as a decentralized autonomous organization or otherwise), Economic Committee or other Members, whether arising in contract, tort, or otherwise, solely by reason of being or acting as a Member.


YOU WILL DEFEND, INDEMNIFY, AND HOLD PROVIDERS HARMLESS FROM ANY CLAIM, DEMAND, LAWSUIT, ACTION, PROCEEDING, INVESTIGATION, LIABILITY, DAMAGE, LOSS, COST OR EXPENSE, INCLUDING WITHOUT LIMITATION REASONABLE ATTORNEYS' FEES, ARISING OUT OF OR RELATING TO YOUR USE OF, OR CONDUCT IN CONNECTION WITH, THE APPLICATIONS; YOUR VIOLATION OF APPLICABLE LAWS OR REGULATIONS; OR YOUR INFRINGEMENT OR MISAPPROPRIATION OF THE RIGHTS OF ANY OTHER PERSON OR ENTITY. 


The Providers do not own or control the underlying software protocols that are used in connection with the supported blockchain networks. In general, the underlying protocols are open-source and anyone can use, copy, modify, and distribute them. In no event will the Providers be responsible for the operation of the underlying protocols and the Providers make no guarantee of the functionality, security, or availability of the Applications. You further acknowledge that the Providers do not check or monitor projects created on the Applications and are not responsible for the activities conducted on the Applications. In no event shall the Providers be in any legal relationship with the creators, participants, the state or any third parties using the Applications. 


NOTHING ON THIS WEBSITE OR THE APPLICATIONS IS INVESTMENT ADVICE, FINANCIAL ADVICE, TRADING ADVICE, OR ANY OTHER SORT OF ADVICE, AND YOU WILL NOT TREAT ANYTHING ON THIS WEBSITE OR THE APPLICATIONS AS SUCH. The Providers do not recommend the buying, selling, or holding of any digital asset. The Applications are provided to you and the Providers neither have control over your transactions, nor encourage you to perform any. Any transaction performed by you via the Applications remains your sole responsibility. You will conduct your own diligence and consult a licensed financial advisor before making any and all investment decisions. Any investments, trades, speculation, or decisions made on the basis of any information found on this website or the Applications, express or implied, are committed at your own risk.


You acknowledge that use of digital assets, cryptocurrencies, and blockchain technology involve a high degree of risk, and that digital assets may have no present or future value. The use or accessing of digital assets may result in a loss of part or all of their value. Digital assets, and the blockchain technology on which they are based, are new and rapidly changing, and therefore may contain technical flaws and may be susceptible to malicious cyberattacks. The Providers are not responsible for any such risks, and are not responsible for any loss or theft of, inability to use, or loss of value related to any digital assets.
