### ISSUE TITLE
Add 'Share' button to vaults UI for Beta campaign marketing engagement 

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#55]
## What is the Problem Being Solved?

*Testnet only*
Marketing have requested the addition of a 'Share' Twitter button that takes user to Twitter with a pre-defined tweet that flaunts how awesome their experience is' (Copy to be provided by Marketing).

## Description of the Design

Add a button that is in line with branding (keep it simple)
reference: https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/guides/parameter-reference1 

-remove before we launch to mainnet

## Security Considerations
TBD
## Test Plan
To be smoke testing during Functional Testing

**Comment by ivanlei** [comment]
This requirement is coming in well past any design phase for the functional release and therefore can't be accommodated. This could be accomplished with non product features - like emails or slack messages exhorting folks to retweet.

**Comment by otoole-brendan** [comment]
@samsiegart let's revisit this during EVP if you have capacity (we can reopen then if so)
