### ISSUE TITLE
Create Vaults UI Jumper page for Decentralized Hosting

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#57]
## What is the Problem Being Solved?

A component of https://github.com/Agoric/agoric-sdk/issues/4350 - we need a jumper page with some JS there that reads the hash and redirects to the published candidate

## Description of the Design
TBD

## Security Considerations
Reviewed by Ari

**Comment by dckc** [comment]
design note from #4350:

Users visit `app.inter.trade` or `wallet.agoric.app`; some JS there reads the hash and redirects to the published candidate
