### ISSUE TITLE
Define and document DCF publishing process in lieu of decentralized UI hosting

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#59]
## What is the Problem Being Solved?
The decentralized UI hosting of Vaults UI on IPFS will operate in collaboration with the DCF and the EC. 
Each will have a part to play in ensuring the Vaults UI sufficiently hosted in a decentralized fashion and is kept up to date

## Description of the Design
The process will be defined in the document.

**Comment by ivanlei** [comment]
Doc from @arirubinstein at https://docs.google.com/document/d/1VwdhfRv23vw8IvSeU799rHzt8pNsCuBAShYw-K1_6WU/edit#

**Comment by otoole-brendan** [comment]
Validated DCF publishing instructions (DCF successfully completed initial publish to IPFS)
