### ISSUE TITLE
Obtaining `ACCOUNT_KEY`

### ISSUE THREAD

**Issue by anilhelvaci** [Agoric/dapp-inter#64]
## What is the Problem Being Solved?

In [README.md -> Development -> Step 3](https://github.com/Agoric/dapp-inter/blob/main/README.md#development) there's the below command;

```sh
agd keys add YOUR_ACCOUNT_KEY --keyring-backend=test // Your test account. You can name this whatever you want.
```

Where can I obtain `YOUR_ACCOUNT_KEY`?  Can I find it under `cosmic-swingset/t1` directory?

Thanks 🙏

**Comment by turadg** [comment]
`YOUR_ACCOUNT_KEY` is the name you choose for the key to be generated by `agd keys add`. That's what "You can name this whatever you want." is meant to convey.

PR welcomed for making this more clear.
