### ISSUE TITLE
use `makeVaultInvitation` from vault manager instead of director

### ISSUE THREAD

**Issue by turadg** [Agoric/dapp-inter#68]
## What is the Problem Being Solved?

The method is being removed from the director: https://github.com/Agoric/agoric-sdk/pull/6983

This will be needed for https://github.com/Agoric/agoric-sdk/issues/6518 also, though that's not scheduled.

## Description of the Design

This will require keeping track of the manager objects and targeting them.

For targeting, instead of this `contract` spec, https://github.com/Agoric/dapp-inter/blob/48fe77a6167d2182317e7097079c3b75fd10b966/src/service/vaults.ts#L361-L364
it wil have to be an `object` spec, blocking on https://github.com/Agoric/agoric-sdk/issues/6850

**Comment by samsiegart** [comment]
>Look up the vault/collateral manager instance

Is this published in vstorage anywhere currently?
