### ISSUE TITLE
As Vaults user creating a new vault, I should be able to get as far as possible in the flow before having to connect my smart wallet (and Keplr wallet?)

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#9]
## What is the Problem Being Solved?

Given previous feedback on PSM, we need to allow users to progress as far as possible in the flow before prompting them to connect their wallet

## Description of the Design

- This point is likely the vault configuration screen

- User should see ‘Connect Wallet’ in place of ‘Confirm’ (previously ‘Configure’) if they haven’t yet connected their wallet. If they have then the opposite is true. (Not yet in Figma design but will be added by Ekko)

## Security Considerations
Unknown
## Test Plan
Smoke Test after implementation

**Comment by dckc** [comment]
> This point is likely the vault configuration screen

Why do they need a keplr wallet to configure a vault?

Keplr shouldn't be needed until they want to sign something, right? Oh... we need to know their address to get their balances at this point?

Aside: grumble: Keplr doesn't separate read-only access to an account from full control. Other wallets let you watch accounts, and would let you connect to provide an address without providing signing capability.

**Comment by samsiegart** [comment]
> Oh... we need to know their address to get their balances at this point?

Yea we need to display purses and balances and provide input validation for them to enter amounts. Also we need to know `{chainId, address}`, when we write the offer to local storage so that wallet.agoric.app/wallet/ knows which account it's for.

**Comment by dckc** [comment]
Writing the offer to localStorage happens *after* they fill out the configuration screen, right? That's pretty much what I meant by "when they want to sign something". But it sounds like we need it to get balances to guide input.

**Comment by dckc** [comment]
@otoole-brendan to my mind, the user story here is "configure a vault", and the how far you can get without needing keplr should be a subordinate detail (an acceptance criterion).

I also suggest that putting "As a Vaults user creating a new vault" in the title makes a lot of things hard to read, so it should only appear in the description. OTOH, I suggested that to @rowgraus quite some time ago, but he wasn't convinced.
