### ISSUE TITLE
User doesn't know minimum initial debt when creating a vault

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#97]
## What is the Problem Being Solved?

When a user is creating a new vault, if they enter desired IST to mint value that is less that the defined minimum initial debt per governed parameter - they get a 'Below Minimum' error. It is not that informative however as user does not know min value they need to enter unless they play around. We should inform user what the minimum value is so they can adjust accordingly.

## Description of the Design

- Show Minimum Initial Debt setting on FE (on Vault Manager Card on Create Vault view) via a more informative message when below Min Debt. 
- Update 'Below Minimum' -> 'Below Minimum of X' (with 'X' being governed parameter value) 

## Security Considerations
N/A
## Test Plan
Will be smoke-tested

**Comment by samsiegart** [comment]
@otoole-brendan The message is a bit too long to fit comfortably, what about just "X minimum"?

**Comment by otoole-brendan** [comment]
Latest per https://agoricopco.slack.com/archives/C038TM0EUKG/p1680553358582629?thread_ts=1680545521.231489&cid=C038TM0EUKG  agreed on 'Below minimum of X'. But punting to V+1
